from model.unet import UNet
#from model.my_unet import MyUnet
from model.unet_dilated import UNetDilated
from model.unet_with_detections import UNetWithDetections
from model.sol_eol_finder import SOL_EOL_Finder
from model.detector import Detector
from model.yolo_box_detector import YoloBoxDetector
from model.pairing_box_full import PairingBoxFull
from model.pairing_box_net import PairingBoxNet
from model.pairing_box_from_gt import PairingBoxFromGT
from model.pairing_graph import PairingGraph
from model.binary_pair_net import BinaryPairNet
from model.graph_net import GraphNet
from model.line_follower import LineFollower
from model.simpleNN import SimpleNN
#from .roi_align import ROIAlign
#from .roi_align import roi_align
